<?php

CswConst::c('PROPORTIONALRESIZE', 'PROPORTIONALRESIZE');
CswConst::c('THUMBNAILRESIZE', 'THUMBNAILRESIZE');
CswConst::c('RESIZEBYHEIGHT', 'RESIZEBYHEIGHT');
CswConst::c('RESIZEBYWIDTH', 'RESIZEBYWIDTH');

?>
